Repository humanmade/altis-documentation, pull requests merged in 2021-08, with the labels that each got.

#260 Add escaping for the asterisks in the command
  other-docs/guides/updating-php/README.md
Labels: backport v7-branch, backport v8-branch

#265 Make the PHP version compat table easier to maintain
  other-docs/guides/updating-php/README.md
Labels: backport v8-branch

#269 Fix PHPCS command
  other-docs/guides/code-review/README.md
Labels: backport v5-branch, backport v6-branch, backport v7-branch, backport v8-branch

#266 Fix dashboard login link
  other-docs/guides/getting-help-with-altis.md
Labels: backport v7-branch, backport v8-branch
